[[social]]
name = "Mail"
pre = '<i class="fas fa-fw fa-at"></i>'
url = "mailto:team@epicenter.works"
weight = 10

[[main]]
name = "Documentation"
url = "https://github.com/AKVorrat/dearmep?tab=readme-ov-file#-documentation"
target = "_blank"
weight = 60


[[footer]]
name = "Legal notice"
url = "https://en.epicenter.works/contact"
target = "_blank"
weight = 10
[[footer]]
name = "Privacy policy"
url = "https://en.epicenter.works/privacy"
weight = 20
