name: Deploy DearMEP site to Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build page
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn install` command
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  # Deployment job
  # deploy-stage:
  #   environment:
  #     name: staging
  #     url: https://stage.dearmep.eu
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: 📂 Sync files
  #       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  #       with:
  #         server: webhost.epicenter.works
  #         username: stage
  #         password: ${{ secrets.ftp_password }}
  #
  # deploy-production:
  #   environment:
  #     name: production
  #     url: https://stage.dearmep.eu
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: 📂 Sync files
  #       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  #       with:
  #         server: webhost.epicenter.works
  #         username: stage
  #         password: ${{ secrets.ftp_password }}
